USE AMAZONSALESDB;
GO

ALTER VIEW VW_CLEANAMAZONSALES AS
SELECT [ORDER_ID] AS ORDERID,
       CAST([DATE] AS DATE) AS ORDERDATE,
       [STATUS] AS ORDERSTATUS,
       [FULFILMENT] AS FULFILLMENTMETHOD,
       [CATEGORY] AS PRODUCTCATEGORY,
       [SIZE] AS PRODUCTSIZE,
       CAST([QTY] AS INT) AS ORDERQUANTITY,
    
       -- HANDLE MISSING VALUES AND CAST TO DECIMAL
       ISNULL(CAST([AMOUNT] AS DECIMAL(10,2)), 0) AS REVENUEINR,
    
       -- CONVERT INR TO USD (APPROXIMATE HISTORICAL RATE OF 0.012 FOR THE DATASET PERIOD)
       CAST(ISNULL(CAST([AMOUNT] AS DECIMAL(10,2)), 0) * 0.012 AS DECIMAL(10,2)) AS REVENUEUSD,
       UPPER([SHIP_CITY]) AS SHIPCITY,
       UPPER([SHIP_STATE]) AS SHIPSTATE,
    
       -- CLEAN UP THE B2B FLAG FOR EASIER VISUALIZATION
       CASE WHEN [B2B] = 'True' THEN 'B2B (Wholesale)' ELSE 'B2C (Retail)' END AS CLIENTTYPE
FROM RAW_AMAZONSALES_WIZARD
WHERE [ORDER_ID] IS NOT NULL 
AND [DATE] IS NOT NULL
AND TRY_CAST([QTY] AS INT) > 0 -- REMOVE 0-QUANTITY ROWS (E.G., CANCELLED BEFORE PROCESSING)
--AND [STATUS] != 'CANCELLED'; -- FOCUS ON ACTUAL GENERATED REVENUE